In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

# Project root
ROOT = Path.cwd().parent

# Raw data paths
WATER_QUALITY_DIR = ROOT / "data" / "raw" / "water_quality"
WEATHER_DIR = ROOT / "data" / "raw" / "weather"

print("Project root:", ROOT)
print("Water-quality files:", list(WATER_QUALITY_DIR.glob("*.csv")))
print("Weather files:", list(WEATHER_DIR.glob("*.csv")))

Project root: C:\Users\AARYA PATEL\OneDrive\Desktop\Github\techstack
Water-quality files: [WindowsPath('C:/Users/AARYA PATEL/OneDrive/Desktop/Github/techstack/data/raw/water_quality/rs_session-241_as196_1.1.csv'), WindowsPath('C:/Users/AARYA PATEL/OneDrive/Desktop/Github/techstack/data/raw/water_quality/RS_Session_255_AU_90.1 (1).csv'), WindowsPath('C:/Users/AARYA PATEL/OneDrive/Desktop/Github/techstack/data/raw/water_quality/RS_Session_255_AU_90.2.csv')]
Weather files: [WindowsPath('C:/Users/AARYA PATEL/OneDrive/Desktop/Github/techstack/data/raw/weather/export (1).csv'), WindowsPath('C:/Users/AARYA PATEL/OneDrive/Desktop/Github/techstack/data/raw/weather/export (2).csv'), WindowsPath('C:/Users/AARYA PATEL/OneDrive/Desktop/Github/techstack/data/raw/weather/export (3).csv'), WindowsPath('C:/Users/AARYA PATEL/OneDrive/Desktop/Github/techstack/data/raw/weather/export (4).csv'), WindowsPath('C:/Users/AARYA PATEL/OneDrive/Desktop/Github/techstack/data/raw/weather/export (5).csv'), WindowsPath('C:/Users/AARYA PATEL/OneDrive/Desktop/Github/techstack/data/raw/weather/export.csv')]

In [2]:
# Load all water-quality CSV files
water_files = sorted(WATER_QUALITY_DIR.glob("*.csv"))

water_data = {}

for file in water_files:
    df = pd.read_csv(file)
    water_data[file.name] = df

    print("=" * 80)
    print("FILE:", file.name)
    print("Shape:", df.shape)
    print("Columns:")
    print(df.columns.tolist())
    print()
    print(df.head(3))

================================================================================
FILE: rs_session-241_as196_1.1.csv
Shape: (10, 17)
Columns:
['Sr. No.', 'LOCATION - Water Quality Criteria', 'DO (mg/l) - 2011 - >5 mg/l', 'DO (mg/l) - 2012 - >5 mg/l', 'DO (mg/l) - 2013 - >5 mg/l', 'DO (mg/l) - 2014 - >5 mg/l', 'DO (mg/l) - 2015 - >5 mg/l', 'B.O.D (mg/l) - 2011 - < 3 mg/l', 'B.O.D (mg/l) - 2012 - < 3 mg/l', 'B.O.D (mg/l) - 2013 - < 3 mg/l', 'B.O.D (mg/l) - 2014 - < 3 mg/l', 'B.O.D (mg/l) - 2015 - < 3 mg/l', 'FECAL COLIFORM (MPN/100ml) - 2011 - < 2500 MPN/100ml', 'FECAL COLIFORM (MPN/100ml) - 2012 - < 2500 MPN/100ml', 'FECAL COLIFORM (MPN/100ml) - 2013 - < 2500 MPN/100ml', 'FECAL COLIFORM (MPN/100ml) - 2014 - < 2500 MPN/100ml', 'FECAL COLIFORM (MPN/100ml) - 2015 - < 2500 MPN/100ml']

   Sr. No. LOCATION - Water Quality Criteria  DO (mg/l) - 2011 - >5 mg/l  \
0        1             GANGA AT HARIDWAR D/S                         6.7
1        2           GANGA AT GARHMUKTESHWAR                         8.2
2        3    GANGA AT KANNAUJ U/S (RAJGHAT)                         7.9

   DO (mg/l) - 2012 - >5 mg/l  DO (mg/l) - 2013 - >5 mg/l  \
0                         7.2                         6.5
1                         8.6                         9.0
2                         8.6                         8.2

   DO (mg/l) - 2014 - >5 mg/l  DO (mg/l) - 2015 - >5 mg/l  \
0                         5.0                         9.2
1                         9.1                         7.7
2                         7.8                         8.4

   B.O.D (mg/l) - 2011 - < 3 mg/l  B.O.D (mg/l) - 2012 - < 3 mg/l  \
0                             5.6                             5.3
1                             3.4                             3.4
2                             4.5                             4.0

   B.O.D (mg/l) - 2013 - < 3 mg/l  B.O.D (mg/l) - 2014 - < 3 mg/l  \
0                             5.2                             5.2
1                             2.9                             2.8
2                             4.0                             2.8

   B.O.D (mg/l) - 2015 - < 3 mg/l  \
0                             2.8
1                             3.0
2                             3.5

   FECAL COLIFORM (MPN/100ml) - 2011 - < 2500 MPN/100ml  \
0                                               1150
1                                               1162
2                                               3042

   FECAL COLIFORM (MPN/100ml) - 2012 - < 2500 MPN/100ml  \
0                                                NaN
1                                              920.0
2                                             4673.0

   FECAL COLIFORM (MPN/100ml) - 2013 - < 2500 MPN/100ml  \
0                                                NaN
1                                              767.0
2                                             1210.0

   FECAL COLIFORM (MPN/100ml) - 2014 - < 2500 MPN/100ml  \
0                                                NaN
1                                              725.0
2                                             3500.0

   FECAL COLIFORM (MPN/100ml) - 2015 - < 2500 MPN/100ml
0                                                580
1                                                733
2                                               2270
================================================================================
FILE: RS_Session_255_AU_90.1 (1).csv
Shape: (93, 8)
Columns:
['State', 'Station Name', 'Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2018', 'Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2019', 'Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2020', 'Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2018', 'Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2019', 'Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2020']

         State                          Station Name  \
0  Uttarakhand                Bhagirathi at Gangotri
1  Uttarakhand  Mandakini b/c Alaknanda, Rudraprayag
2  Uttarakhand  Alaknanda b/c Mandakini, RudraPrayag

   Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2018  \
0                                                8.8
1                                                9.2
2                                                9.2

   Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2019  \
0                                               10.3
1                                                9.5
2                                                9.7

   Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2020  \
0                                                9.8
1                                                9.8
2                                                9.4

   Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2018  \
0                                                7.0
1                                              450.0
2                                             2300.0

   Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2019  \
0                                                7.0
1                                                1.9
2                                                1.9

   Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2020
0                                                2.0
1                                                1.8
2                                                1.8
================================================================================
FILE: RS_Session_255_AU_90.2.csv
Shape: (84, 4)
Columns:
['Station Code', 'Station Name', 'Parameters - Dissolved Oxygen (mg/l) - (Criteria >5.0 mg/l)', 'Parameters - Faecal coliform (MPN/100 ml) - (Criteria <2500 MPN/100 ml)']

  Station Code                          Station Name  \
0  Uttarakhand  Mandakini b/c Alaknanda, Rudraprayag
1  Uttarakhand  Alaknanda b/c Mandakini, Rudraprayag
2  Uttarakhand  Alkananda a/c Mandakini, Rudraprayag

   Parameters - Dissolved Oxygen (mg/l) - (Criteria >5.0 mg/l)  \
0                                               10.4
1                                               10.2
2                                               10.4

   Parameters - Faecal coliform (MPN/100 ml) - (Criteria <2500 MPN/100 ml)
0                                                1.8
1                                                1.8
2                                                1.8

In [3]:
# Load all weather CSV files
weather_files = sorted(WEATHER_DIR.glob("*.csv"))

weather_data = {}

for file in weather_files:
    df = pd.read_csv(file)
    weather_data[file.name] = df

    print("=" * 80)
    print("FILE:", file.name)
    print("Shape:", df.shape)
    print("Columns:")
    print(df.columns.tolist())
    print()
    print(df.head(3))

================================================================================
FILE: export (1).csv
Shape: (192, 12)
Columns:
['time', 'temp', 'dwpt', 'rhum', 'prcp', 'snow', 'wdir', 'wspd', 'wpgt', 'pres', 'tsun', 'coco']

                  time  temp  dwpt  rhum  prcp  snow  wdir  wspd  wpgt  \
0  2026-08-07 00:30:00  27.1  26.4    96   0.0   NaN   165   4.0   NaN
1  2026-08-07 01:30:00  27.0  26.5    97   0.2   NaN    88   2.9   NaN
2  2026-08-07 02:30:00  26.7  26.4    98   0.0   NaN    83   2.9   NaN

     pres  tsun  coco
0  1000.5   NaN     3
1   999.9   NaN     7
2   999.7   NaN     3
================================================================================
FILE: export (2).csv
Shape: (192, 12)
Columns:
['time', 'temp', 'dwpt', 'rhum', 'prcp', 'snow', 'wdir', 'wspd', 'wpgt', 'pres', 'tsun', 'coco']

                  time  temp  dwpt  rhum  prcp  snow  wdir  wspd  wpgt   pres  \
0  2026-08-07 00:30:00  27.5  25.7    90   NaN   NaN   241   3.7   NaN  999.6
1  2026-08-07 01:30:00  27.4  25.8    91   NaN   NaN   237   3.7   NaN  999.1
2  2026-08-07 02:30:00  27.2  25.8    92   NaN   NaN   233   3.7   NaN  998.7

   tsun  coco
0   NaN     4
1   NaN     4
2   NaN     4
================================================================================
FILE: export (3).csv
Shape: (192, 12)
Columns:
['time', 'temp', 'dwpt', 'rhum', 'prcp', 'snow', 'wdir', 'wspd', 'wpgt', 'pres', 'tsun', 'coco']

                  time  temp  dwpt  rhum  prcp  snow  wdir  wspd  wpgt  \
0  2026-08-07 00:30:00  25.5  24.6    95   0.7   NaN    10   7.2   NaN
1  2026-08-07 01:30:00  25.1  24.6    97   3.0   NaN    88   6.8   NaN
2  2026-08-07 02:30:00  25.1  24.8    98   0.5   NaN   116   4.7   NaN

     pres  tsun  coco
0  1001.2   NaN    17
1  1000.4   NaN     9
2  1000.0   NaN     8
================================================================================
FILE: export (4).csv
Shape: (192, 12)
Columns:
['time', 'temp', 'dwpt', 'rhum', 'prcp', 'snow', 'wdir', 'wspd', 'wpgt', 'pres', 'tsun', 'coco']

                  time  temp  dwpt  rhum  prcp  snow  wdir  wspd  wpgt  \
0  2026-08-07 00:30:00  25.2  23.8    92   0.0   NaN    56   6.1   NaN
1  2026-08-07 01:30:00  25.1  23.5    91   1.3   NaN    65   6.5   NaN
2  2026-08-07 02:30:00  24.8  23.2    91   1.9   NaN    46   4.3   NaN

     pres  tsun  coco
0  1002.4   NaN     3
1  1001.8   NaN     9
2  1001.4   NaN     9
================================================================================
FILE: export (5).csv
Shape: (192, 12)
Columns:
['time', 'temp', 'dwpt', 'rhum', 'prcp', 'snow', 'wdir', 'wspd', 'wpgt', 'pres', 'tsun', 'coco']

                  time  temp  dwpt  rhum  prcp  snow  wdir  wspd  wpgt  pres  \
0  2026-08-07 00:30:00    28  26.9    94   0.0   NaN     0     0   NaN  1000
1  2026-08-07 01:30:00    28  26.9    94   0.0   NaN     0     0   NaN   999
2  2026-08-07 02:30:00    28  26.9    94   0.0   NaN     0     0   NaN   999

   tsun  coco
0   NaN     5
1   NaN     5
2   NaN     5
================================================================================
FILE: export.csv
Shape: (192, 12)
Columns:
['time', 'temp', 'dwpt', 'rhum', 'prcp', 'snow', 'wdir', 'wspd', 'wpgt', 'pres', 'tsun', 'coco']

                  time  temp  dwpt  rhum  prcp  snow  wdir  wspd  wpgt   pres  \
0  2026-08-07 00:30:00  26.1  25.4    96   0.0   NaN   172   7.6   NaN  999.6
1  2026-08-07 01:30:00  26.0  25.3    96   0.2   NaN   167   7.2   NaN  998.9
2  2026-08-07 02:30:00  26.1  25.2    95   0.0   NaN   170   6.8   NaN  998.5

   tsun  coco
0   NaN     3
1   NaN     7
2   NaN     3

In [4]:
# ---------------------------------------------------------
# Detailed inspection of water-quality datasets
# ---------------------------------------------------------

for name, df in water_data.items():
    print("=" * 100)
    print(f"FILE: {name}")
    print(f"Rows: {len(df)}")
    print(f"Columns: {len(df.columns)}")
    print()

    print("Data types:")
    print(df.dtypes)
    print()

    print("Missing values:")
    print(df.isna().sum())
    print()

    # Show station/location column if available
    station_columns = [
        col for col in df.columns
        if any(key in col.lower() for key in ["location", "station"])
    ]

    for col in station_columns:
        print(f"Unique values in '{col}': {df[col].nunique()}")
        print(df[col].dropna().unique()[:30])
        print()

    print("-" * 100)

====================================================================================================
FILE: rs_session-241_as196_1.1.csv
Rows: 10
Columns: 17

Data types:
Sr. No.                                                   int64
LOCATION - Water Quality Criteria                           str
DO (mg/l) - 2011 - >5 mg/l                              float64
DO (mg/l) - 2012 - >5 mg/l                              float64
DO (mg/l) - 2013 - >5 mg/l                              float64
DO (mg/l) - 2014 - >5 mg/l                              float64
DO (mg/l) - 2015 - >5 mg/l                              float64
B.O.D (mg/l) - 2011 - < 3 mg/l                          float64
B.O.D (mg/l) - 2012 - < 3 mg/l                          float64
B.O.D (mg/l) - 2013 - < 3 mg/l                          float64
B.O.D (mg/l) - 2014 - < 3 mg/l                          float64
B.O.D (mg/l) - 2015 - < 3 mg/l                          float64
FECAL COLIFORM (MPN/100ml) - 2011 - < 2500 MPN/100ml      int64
FECAL COLIFORM (MPN/100ml) - 2012 - < 2500 MPN/100ml    float64
FECAL COLIFORM (MPN/100ml) - 2013 - < 2500 MPN/100ml    float64
FECAL COLIFORM (MPN/100ml) - 2014 - < 2500 MPN/100ml    float64
FECAL COLIFORM (MPN/100ml) - 2015 - < 2500 MPN/100ml      int64
dtype: object

Missing values:
Sr. No.                                                 0
LOCATION - Water Quality Criteria                       0
DO (mg/l) - 2011 - >5 mg/l                              0
DO (mg/l) - 2012 - >5 mg/l                              0
DO (mg/l) - 2013 - >5 mg/l                              0
DO (mg/l) - 2014 - >5 mg/l                              0
DO (mg/l) - 2015 - >5 mg/l                              0
B.O.D (mg/l) - 2011 - < 3 mg/l                          0
B.O.D (mg/l) - 2012 - < 3 mg/l                          0
B.O.D (mg/l) - 2013 - < 3 mg/l                          0
B.O.D (mg/l) - 2014 - < 3 mg/l                          0
B.O.D (mg/l) - 2015 - < 3 mg/l                          0
FECAL COLIFORM (MPN/100ml) - 2011 - < 2500 MPN/100ml    0
FECAL COLIFORM (MPN/100ml) - 2012 - < 2500 MPN/100ml    1
FECAL COLIFORM (MPN/100ml) - 2013 - < 2500 MPN/100ml    1
FECAL COLIFORM (MPN/100ml) - 2014 - < 2500 MPN/100ml    1
FECAL COLIFORM (MPN/100ml) - 2015 - < 2500 MPN/100ml    0
dtype: int64

Unique values in 'LOCATION - Water Quality Criteria': 10
<ArrowStringArray>
[                       'GANGA AT HARIDWAR D/S',
                      'GANGA AT GARHMUKTESHWAR',
               'GANGA AT KANNAUJ U/S (RAJGHAT)',
                    'GANGA AT KANNAUJ D/S, U.P',
               'GANGA AT KANPUR U/S (RANIGHAT)',
 'GANGA AT KANPUR D/S (JAJMAU PUMPING STATION)',
        'GANGA AT ALLAHABAD D/S (SANGAM), U.P.',
  'GANGA AT VARANASI D/S (MALVIYA BRIDGE), U.P',
                  'GANGA AT TRIGHAT (GHAZIPUR)',
                       'GANGA AT DAKSHINESHWAR']
Length: 10, dtype: str

----------------------------------------------------------------------------------------------------
====================================================================================================
FILE: RS_Session_255_AU_90.1 (1).csv
Rows: 93
Columns: 8

Data types:
State                                                                                 str
Station Name                                                                          str
Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2018               float64
Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2019               float64
Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2020               float64
Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2018    float64
Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2019    float64
Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2020    float64
dtype: object

Missing values:
State                                                                              0
Station Name                                                                       0
Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2018                3
Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2019                0
Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2020                0
Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2018    14
Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2019     5
Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2020     5
dtype: int64

Unique values in 'Station Name': 93
<ArrowStringArray>
[                        'Bhagirathi at Gangotri',
           'Mandakini b/c Alaknanda, Rudraprayag',
           'Alaknanda b/c Mandakini, RudraPrayag',
           'Alkananda a/c Mandakini, Rudraprayag',
            'Bhagirathi b/c Alaknanda, Devprayag',
            'Alaknanda b/c Bhagirathi, Devprayag',
            'Alaknanda a/c Bhagirathi, Devprayag',
                                 'U/s Rishikesh ',
 'A/c Song Near Satyanarayan Temple, d/s Raiwala',
                                  'Rishikesh d/s',
                             'Har-ki- pauri Ghat',
                                   'Haridwar d/s',
                                    'Roorkee d/s',
                  'Madhya Ganga Barrage (Bijnor)',
                                 'Garhmukteshwar',
                        'Brijghat Gharmukteshwar',
                                'U/s Anoopshahar',
                                'Anoopshahar d/s',
                           'Narora (Bulandsahar)',
                         'Kachhla Ghat (Aligarh)',
                                    'Farrukhabad',
                          'U/s Kannauj (Rajghat)',
                                    'Kannauj d/s',
                               'Bithoor (Kanpur)',
                          'U/s Kanpur (Ranighat)',
                      'Bathing Ghat (Bharaoghat)',
                                 'Shuklaganj d/s',
                       'Bathing Ghat (Gola Ghat)',
            'Kanpur d/s (Jajmau Pumping Station)',
                   'Bathing Ghat (Jajmau Bridge)']
Length: 30, dtype: str

----------------------------------------------------------------------------------------------------
====================================================================================================
FILE: RS_Session_255_AU_90.2.csv
Rows: 84
Columns: 4

Data types:
Station Code                                                                   str
Station Name                                                                   str
Parameters - Dissolved Oxygen (mg/l) - (Criteria >5.0 mg/l)                float64
Parameters - Faecal coliform (MPN/100 ml) - (Criteria <2500 MPN/100 ml)    float64
dtype: object

Missing values:
Station Code                                                               0
Station Name                                                               0
Parameters - Dissolved Oxygen (mg/l) - (Criteria >5.0 mg/l)                0
Parameters - Faecal coliform (MPN/100 ml) - (Criteria <2500 MPN/100 ml)    4
dtype: int64

Unique values in 'Station Code': 5
<ArrowStringArray>
['Uttarakhand', 'Uttar Pradesh', 'Bihar', 'Jharkhand', 'West Bengal']
Length: 5, dtype: str

Unique values in 'Station Name': 84
<ArrowStringArray>
[          'Mandakini b/c Alaknanda, Rudraprayag',
           'Alaknanda b/c Mandakini, Rudraprayag',
           'Alkananda a/c Mandakini, Rudraprayag',
            'Bhagirathi b/c Alaknanda, Devprayag',
            'Alaknanda b/c Bhagirathi, Devprayag',
            'Alaknanda a/c Bhagirathi, Devprayag',
                                  'U/s Rishikesh',
 'A/c Song Near Satyanarayan Temple, d/s Raiwala',
                                  'Rishikesh d/s',
                             'Har-ki- pauri Ghat',
                                   'Haridwar d/s',
                                    'Roorkee d/s',
                  'Madhya Ganga Barrage (Bijnor)',
                                 'Garhmukteshwar',
                        'Brijghat Gharmukteshwar',
                                'U/s Anoopshahar',
                                'Anoopshahar d/s',
                           'Narora (Bulandsahar)',
                         'Kachhla Ghat (Aligarh)',
                                    'Farrukhabad',
                          'U/s Kannauj (Rajghat)',
                                    'Kannauj d/s',
                               'Bithoor (Kanpur)',
                          'U/s Kanpur (Ranighat)',
                      'Bathing Ghat (Bharaoghat)',
                                 'Shuklaganj d/s',
                       'Bathing Ghat (Gola Ghat)',
            'Kanpur d/s (Jajmau Pumping Station)',
                   'Bathing Ghat (Jajmau Bridge)',
                          'Dalmau (Rai Bareilly)']
Length: 30, dtype: str

----------------------------------------------------------------------------------------------------

In [5]:
# ---------------------------------------------------------
# Check possible duplicate station names
# ---------------------------------------------------------

for name, df in water_data.items():

    station_columns = [
        col for col in df.columns
        if any(key in col.lower() for key in ["location", "station"])
    ]

    if station_columns:
        print("=" * 100)
        print(name)

        for col in station_columns:
            duplicates = (
                df[col]
                .dropna()
                .value_counts()
                .loc[lambda x: x > 1]
            )

            print(f"\nDuplicate values in {col}:")
            print(duplicates if not duplicates.empty else "None")

====================================================================================================
rs_session-241_as196_1.1.csv

Duplicate values in LOCATION - Water Quality Criteria:
None
====================================================================================================
RS_Session_255_AU_90.1 (1).csv

Duplicate values in Station Name:
None
====================================================================================================
RS_Session_255_AU_90.2.csv

Duplicate values in Station Code:
Station Code
Bihar            33
Uttar Pradesh    30
Uttarakhand      12
West Bengal       5
Jharkhand         4
Name: count, dtype: int64

Duplicate values in Station Name:
None

In [6]:
# ---------------------------------------------------------
# Convert the 2011-2015 water-quality file to long format
# ---------------------------------------------------------

file_2011_2015 = water_data["rs_session-241_as196_1.1.csv"].copy()

station_col = "LOCATION - Water Quality Criteria"

records = []

for _, row in file_2011_2015.iterrows():
    station = row[station_col]

    for year in range(2011, 2016):
        record = {
            "station_name": station,
            "year": year,
            "dissolved_oxygen": row[
                f"DO (mg/l) - {year} - >5 mg/l"
            ],
            "bod": row[
                f"B.O.D (mg/l) - {year} - < 3 mg/l"
            ],
            "fecal_coliform": row[
                f"FECAL COLIFORM (MPN/100ml) - {year} - < 2500 MPN/100ml"
            ],
            "source_file": "rs_session-241_as196_1.1.csv",
        }

        records.append(record)

water_2011_2015_long = pd.DataFrame(records)

water_2011_2015_long.head(15)

,station_name,year,dissolved_oxygen,bod,fecal_coliform,source_file
0,GANGA AT HARIDWAR D/S,2011,6.7,5.6,1150.0,rs_session-241_as196_1.1.csv
1,GANGA AT HARIDWAR D/S,2012,7.2,5.3,NaN,rs_session-241_as196_1.1.csv
2,GANGA AT HARIDWAR D/S,2013,6.5,5.2,NaN,rs_session-241_as196_1.1.csv
3,GANGA AT HARIDWAR D/S,2014,5.0,5.2,NaN,rs_session-241_as196_1.1.csv
4,GANGA AT HARIDWAR D/S,2015,9.2,2.8,580.0,rs_session-241_as196_1.1.csv
5,GANGA AT GARHMUKTESHWAR,2011,8.2,3.4,1162.0,rs_session-241_as196_1.1.csv
6,GANGA AT GARHMUKTESHWAR,2012,8.6,3.4,920.0,rs_session-241_as196_1.1.csv
7,GANGA AT GARHMUKTESHWAR,2013,9.0,2.9,767.0,rs_session-241_as196_1.1.csv
8,GANGA AT GARHMUKTESHWAR,2014,9.1,2.8,725.0,rs_session-241_as196_1.1.csv
9,GANGA AT GARHMUKTESHWAR,2015,7.7,3.0,733.0,rs_session-241_as196_1.1.csv
10,GANGA AT KANNAUJ U/S (RAJGHAT),2011,7.9,4.5,3042.0,rs_session-241_as196_1.1.csv
11,GANGA AT KANNAUJ U/S (RAJGHAT),2012,8.6,4.0,4673.0,rs_session-241_as196_1.1.csv
12,GANGA AT KANNAUJ U/S (RAJGHAT),2013,8.2,4.0,1210.0,rs_session-241_as196_1.1.csv
13,GANGA AT KANNAUJ U/S (RAJGHAT),2014,7.8,2.8,3500.0,rs_session-241_as196_1.1.csv
14,GANGA AT KANNAUJ U/S (RAJGHAT),2015,8.4,3.5,2270.0,rs_session-241_as196_1.1.csv

In [7]:
water_2011_2015_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   station_name      50 non-null     str
 1   year              50 non-null     int64
 2   dissolved_oxygen  50 non-null     float64
 3   bod               50 non-null     float64
 4   fecal_coliform    47 non-null     float64
 5   source_file       50 non-null     str
dtypes: float64(3), int64(1), str(2)
memory usage: 5.3 KB

In [8]:
water_2011_2015_long.isna().sum()

station_name        0
year                0
dissolved_oxygen    0
bod                 0
fecal_coliform      3
source_file         0
dtype: int64

In [9]:
# ---------------------------------------------------------
# Inspect the third water-quality file properly
# ---------------------------------------------------------

file_3 = water_data["RS_Session_255_AU_90.2.csv"].copy()

print("Shape:", file_3.shape)
print("\nColumns:")
print(file_3.columns.tolist())

print("\nFirst 10 rows:")
display(file_3.head(10))

print("\nMissing values:")
display(file_3.isna().sum())

Shape: (84, 4)

Columns:
['Station Code', 'Station Name', 'Parameters - Dissolved Oxygen (mg/l) - (Criteria >5.0 mg/l)', 'Parameters - Faecal coliform (MPN/100 ml) - (Criteria <2500 MPN/100 ml)']

First 10 rows:

,Station Code,Station Name,Parameters - Dissolved Oxygen (mg/l) - (Criteria >5.0 mg/l),Parameters - Faecal coliform (MPN/100 ml) - (Criteria <2500 MPN/100 ml)
0,Uttarakhand,"Mandakini b/c Alaknanda, Rudraprayag",10.4,1.8
1,Uttarakhand,"Alaknanda b/c Mandakini, Rudraprayag",10.2,1.8
2,Uttarakhand,"Alkananda a/c Mandakini, Rudraprayag",10.4,1.8
3,Uttarakhand,"Bhagirathi b/c Alaknanda, Devprayag",9.9,1.8
4,Uttarakhand,"Alaknanda b/c Bhagirathi, Devprayag",9.7,1.8
5,Uttarakhand,"Alaknanda a/c Bhagirathi, Devprayag",10.0,1.8
6,Uttarakhand,U/s Rishikesh,10.3,14.0
7,Uttarakhand,"A/c Song Near Satyanarayan Temple, d/s Raiwala",9.9,64.0
8,Uttarakhand,Rishikesh d/s,9.8,13.5
9,Uttarakhand,Har-ki- pauri Ghat,9.5,41.5

Missing values:

Station Code                                                               0
Station Name                                                               0
Parameters - Dissolved Oxygen (mg/l) - (Criteria >5.0 mg/l)                0
Parameters - Faecal coliform (MPN/100 ml) - (Criteria <2500 MPN/100 ml)    4
dtype: int64

In [10]:
file_2 = water_data["RS_Session_255_AU_90.1 (1).csv"].copy()

print("Shape:", file_2.shape)
print("\nColumns:")
print(file_2.columns.tolist())

print("\nFirst 10 rows:")
display(file_2.head(10))

print("\nMissing values:")
display(file_2.isna().sum())

Shape: (93, 8)

Columns:
['State', 'Station Name', 'Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2018', 'Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2019', 'Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2020', 'Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2018', 'Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2019', 'Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2020']

First 10 rows:

,State,Station Name,Parameters - Dissolved Oxygen (mg/l) - (Criteria ?5.0 mg/l) - 2018,Parameters - Dissolved Oxygen (mg/l) - (Criteria ?5.0 mg/l) - 2019,Parameters - Dissolved Oxygen (mg/l) - (Criteria ?5.0 mg/l) - 2020,Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2018,Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2019,Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2020
0,Uttarakhand,Bhagirathi at Gangotri,8.8,10.3,9.8,7.0,7.0,2.0
1,Uttarakhand,"Mandakini b/c Alaknanda, Rudraprayag",9.2,9.5,9.8,450.0,1.9,1.8
2,Uttarakhand,"Alaknanda b/c Mandakini, RudraPrayag",9.2,9.7,9.4,2300.0,1.9,1.8
3,Uttarakhand,"Alkananda a/c Mandakini, Rudraprayag",9.2,9.7,10.1,780.0,1.9,1.8
4,Uttarakhand,"Bhagirathi b/c Alaknanda, Devprayag",9.2,9.7,10.0,36.0,1.9,1.8
5,Uttarakhand,"Alaknanda b/c Bhagirathi, Devprayag",9.2,9.5,10.0,780.0,1.9,1.8
6,Uttarakhand,"Alaknanda a/c Bhagirathi, Devprayag",9.4,9.7,10.6,490.0,1.9,1.8
7,Uttarakhand,U/s Rishikesh,9.8,10.1,10.6,NaN,17.0,12.0
8,Uttarakhand,"A/c Song Near Satyanarayan Temple, d/s Raiwala",8.8,9.1,9.0,NaN,110.0,50.0
9,Uttarakhand,Rishikesh d/s,9.6,9.7,9.8,NaN,30.0,22.0

Missing values:

State                                                                              0
Station Name                                                                       0
Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2018                3
Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2019                0
Parameters - Dissolved Oxygen (mg/l)  - (Criteria ?5.0 mg/l) - 2020                0
Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2018    14
Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2019     5
Parameters - Faecal Coliform (MPN/100 ml) - (Criteria ?2500 MPN/100 ml) - 2020     5
dtype: int64